version: "2"

services:
    fluentdui:
        build:
            context: .
            dockerfile: DockerfileFluentdUI
        volumes:
            - $PWD/tmp:/tmp
        ports:
            # fluentd
            #- 24224:24224
            # fluentd-ui
            - 9292:9292
    apache:
        image: httpd:2.4
        volumes:
            # mount log directory to host
            - $PWD/tmp/apache2:/var/log/apache2
            - $PWD/files/apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
        ports:
            - 81:80
    nginx:
        image: nginx:1.11
        volumes:
            # mount log directory to host
            - $PWD/tmp/nginx:/var/log/nginx
        ports:
            - 82:80
    postgres:
        image: postgres:9.4
        volumes:
            # configure postgres log to csv
            # see configure problem with postgres image
            # at https://github.com/docker-library/postgres/issues/105
            # this pull https://github.com/docker-library/postgres/pull/120 doesn't work as expected
            - $PWD/set-config.sh:/docker-entrypoint-initdb.d/set-config.sh
            - $PWD/files/postgres/data/postgresql.conf:/postgresql.conf
            # mount log directory to host
            - $PWD/tmp/postgres:/var/log/postgresql
        ports:
            - 5432:5432
