version: "2"
services:
  fluent:
    build: .
    ports:
      - 24224:24224
    links:
      - mysql:mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.16
    ports:
      - 3306
    volumes:
      - ./fluent_schema.sql:/docker-entrypoint-initdb.d/fluent_schema.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=fluent
      - MYSQL_USER=fluent
      - MYSQL_PASSWORD=fluent_pass
